# These are supported funding model platforms

github: [OrlandoHC]
patreon: 
open_collective: # Replace with a single Open Collective username
ko_fi: 
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
custom: # https://orlandohc.online